package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_constants",
    hdrs = ["test_constants.h"],
)

cc_library(
    name = "test_utils",
    srcs = ["test_utils.cpp"],
    hdrs = ["test_utils.h"],
    deps = [
        ":test_constants"
    ]
)
